### PR TITLE
rebuild

### PR DESCRIPTION
**Pull request by wangshilong**
PR-repos-el7: daos@PR-6752
PR-repos-el8: daos@PR-6752
PR-repos-leap15: daos@PR-6752
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

### CODE REVIEW

**Comment by wangshilong** [comment]
@brianjmurrell 

Looks we need install gnu-mpich package for leap15?

Z] Lmod has detected the following error: The following module(s) are unknown:
[2021-11-11T17:13:27.786Z] "gnu-mpich"
[2021-11-11T17:13:27.786Z] Please check the spelling or version number. Also try "module spider ..."
[2021-11-11T17:13:27.786Z] It is also possible your cache file is out-of-date; it may help to try:
[2021-11-11T17:13:27.786Z]   $ module --ignore-cache load "gnu-mpich"
[2021-11-11T17:13:27.786Z] Also make sure that all modulefiles written in TCL start with the string
[2021-11-11T17:13:27.786Z] #%Module
[2021-11-11T17:13:27.786Z] + eval false
[2021-11-11T17:13:27.786Z] ++ false
[2021-11-11T17:13:27.786Z] RPM build errors:
[2021-11-11T17:13:27.786Z] error: Bad exit status from /var/tmp/rpm-tmp.gicbNV (%build)
[2021-11-11T17:13:27.786Z]     Bad exit status from /var/tmp/rpm-tmp.gicbNV (%build)
[2021-11-11T17:13:27.786Z] Child return code was: 1

**Comment by brianjmurrell** [comment]
> @brianjmurrell
> 
> Looks we need install gnu-mpich package for leap15?

It's already installed but _lua-lmod_'s `module` command doesn't know how to find it.  I've pushed a commit to fix that.

**Comment by wangshilong** [comment]
@brianjmurrell There is no Leap15 RPMS generated for this.

**Comment by johannlombardi** [comment]
Talking with Mohamad, it sounds like this one is not required.

**Pull request closed without merging**
